### ISSUE TITLE
bin/apex-api-gateway has DOS line endings, fails on unix

### ISSUE THREAD

**Issue by ghost** [YoruNoHikage/apex-api-gateway#1]
Hi,

apex-api-gateway cannot be run on Linux (and probably other unix platforms) because the file is saved in DOS format with CRLF line endings:

`/usr/bin/env: ‘node\r’: No such file or directory`

**Comment by YoruNoHikage** [comment]
Thanks, this should be okay now. Let me know if there's still a problem. :)
