### ISSUE TITLE
Syntax error running apex-api-gateway

### ISSUE THREAD

**Issue by mikereinhold** [YoruNoHikage/apex-api-gateway#7]
Immediately after installing apex-api-gateway 0.2.1 via 

```
npm install -g apex-api-gateway
```

apex-api-gateway fails every time with a Syntax error:

```
$ apex-api-gateway -h
apex-api-gateway/index.js:25
function create({ name, description = null, cloneFrom = '', config = './project.json', force }) {
                ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3 
```

**Comment by YoruNoHikage** [comment]
Which version of Node are you using?

**Comment by mikereinhold** [comment]
Thanks for the quick response - I'm hoping we can get this resolved as I really want to try this out :)

```
$ node --version
v4.2.4
```

**Comment by YoruNoHikage** [comment]
I see... I'm using destructuring feature that's not available in this node version. See http://node.green/#destructuring--declarations

I'll fix that as soon as I get some time. In the meantime, you might want to update your Node to give it a try. :)

**Comment by mikereinhold** [comment]
Ah! Makes sense :)

I'll upgrade to 6.8.1 then as that looks like the required milestone for destructuring features. Thanks!

**Comment by mikereinhold** [comment]
Works as expected! Thanks :)
